# App
name = "ImThemes"
comment = "ImThemes is a Dear ImGui theme designer and browser written in Nim"
version = "0.2.3"
website = "https://github.com/Patitotective/ImThemes"
authors = ["Patitotective <https://github.com/Patitotective>"]
categories = ["Utility"]

# AppImage
ghRepo = "Patitotective/ImThemes"

stylePath = "assets/style.toml"
iconPath = "assets/icon.png"
svgIconPath = "assets/icon.svg"
iconFontPath = "assets/forkawesome-webfont.ttf"
fontPath = "assets/Karla-Regular.ttf"
strongFontPath = "assets/Karla-Bold.ttf"
fontSize = 18.0

# Window
minSize = [700, 500] # Width, height
